Resources:
  ChildOfChildStack2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/{TEMPLATE_BUCKET}/child-cfn/child-cfn.yaml
Outputs:
  BucketName:
    Value: !GetAtt ChildOfChildStack2.Outputs.BucketName
