Resources:
  cfnEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-c481fad3
      InstanceType: t2.micro
      KeyName: !Ref "AWS::NoValue"
      SecurityGroups:
        - !Ref cfnSecurityGroup
  cfnSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Open HTTP and SSH ports"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIpv6: ::/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
Outputs:
  SecurityGroup:
    Value: !GetAtt
      - cfnSecurityGroup
      - GroupId
    Description: EC2 Security GroupId
# aws cloudformation create-stack --stack-name ec2-sg-cfn --template-body file://./01-ec2-sg-cfn.yaml
