Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'

Conditions:
  hasKeyPair:
    !Not [!Equals [!Ref KeyName, ""]]

Resources:
  cfnEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-c481fad3
      InstanceType: t2.micro
      KeyName: !If [hasKeyPair, !Ref KeyName, !Ref "AWS::NoValue"]
      SecurityGroups:
        - !Ref cfnSecurityGroup
  cfnSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Open HTTP and SSH ports"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIpv6: ::/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
Outputs:
  SecurityGroup:
    Value: !GetAtt
      - cfnSecurityGroup
      - GroupId
    Description: EC2 Security GroupId

# Sample commandline script

# aws --region us-east-1 cloudformation create-stack --stack-name ec2-sg-cfn --template-body file://./01-ec2-sg-cfn.yaml \
# --parameters ParameterKey=KeyName,ParameterValue=TestKey ParameterKey=SubnetIDs,ParameterValue=SubnetID1
