Resources:
  cfnOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'CloudFront Origin Access Identity'

Outputs:
  s3CanonicalUserId:
    Value: !GetAtt ["cfnOriginAccessIdentity", "S3CanonicalUserId"]
    Description: S3 Canonical User Id
  OriginAccessIdentity:
    Value: !Ref cfnOriginAccessIdentity
    Description: CloudFront Origin Access Identity
# aws --region us-east-1 cloudformation create-stack --stack-name test-cfn --template-body file://./04-origin-access-identity-cfn.yaml
